Bug fix: getNodeList returning int32 max when node id < int32 max.
gmag11/painlessMesh pull request #4
Opened 2017-02-11 17:51 UTC by Derrick-

When nodeid was greater than 2147483647 (i.e., MSB is set), node list would contain 2147483647 instead of the true node id.

Use strtoul to parse nodeid from json instead of String.ToInt().

2017-02-12 07:07 UTC, gmag11 commented
You're right! Thank you

2017-02-12 07:37 UTC, gmag11 commented
I'll make a merge request in main repository on GitLab

2017-02-12 08:02 UTC, gmag11 requested changes

2017-02-12 08:02 UTC, gmag11 commented on src/painlessMeshConnection.cpp
> +        uint32_t id = strtoul(temp.c_str(), &stopstr, 10);
Couldn't this be `uint32_t id = strtoul(temp.c_str(), NULL, 10);` ?

2017-02-13 17:21 UTC, Derrick- commented on src/painlessMeshConnection.cpp
> +        uint32_t id = strtoul(temp.c_str(), &stopstr, 10);
Yes, thanks. Sorry for the delay, wasn't getting noticifcations.

2017-02-15 07:59 UTC, merged

2018-01-16 19:25 UTC, pedrofelipest commented
The numeric identifier of the nodeid changes when the node is restarted or is it still the same when it is disconnected and reconnected?

2018-01-16 21:41 UTC, gmag11 commented
It is always fixed and unique for every device